name: Test with coverage
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          gradle-home-cache-cleanup: true
      - name: Run test
        run: |
          ./gradlew clean
          ./gradlew test
      - name: JaCoCo Coverage Report
        env:
          report_path: BinarySearchTrees/build/jacoco/report.csv
        run: |
          awk -F"," '{ instructions += $4 + $5; covered += $5; branches += $6 + $7; branches_covered +=$7 } END { print "Instructions covered:", covered"/"instructions, "--", 100*covered/instructions"%"; print "Branches covered:", branches_covered"/"branches, "--", 100*branches_covered/branches"%" }' $report_path
      - uses: actions/upload-artifact@v3
        with:
          name: binarysearchtree-test-and-coverage-reports
          path: |
            BinarySearchTrees/build/reports